adds a default clearml-core service account for the core components
allegroai/clearml-helm-charts pull request #253
Opened 2023-08-24 19:07 UTC by thoraxe

**What this PR does / why we need it**:
This PR adds a default service account declaration to the clearml components (webserver, fileserver, apiserver) and a YAML to the chart to create that SA. 

**Checklist**
- [X] Reviewed the [`CONTRIBUTING.md`](https://github.com/allegroai/clearml-helm-charts/blob/main/CONTRIBUTING.md#pull-requests) guide (**required**)
- [X] Verify the work you plan to merge addresses an existing [issue](https://github.com/allegroai/clearml-helm-charts/issues) (If not, open a new one) (**required**)
- [X] Check your branch with `helm lint` (**required**)
- [X] Update `version` in `Chart.yaml` according [semver](https://semver.org/) rules (**required**)
- [X] Substitute `annotations` section in `Chart.yaml` annotating implementations (useful for Artifecthub changelog) (**required**)
- [ ] Update chart README using [helm-docs](https://github.com/norwoodj/helm-docs) (**required**)

**Which issue(s) this PR fixes**:
Fixes #247 

**Special notes for your reviewer**:
It's not entirely a complete PR because it should either do one of two things, which I'm not entirely sure how to do:

1) enable or disable using the ServiceAccount at all
2) create individual SAs for each component based on the name specified in `values.yaml`

2023-08-30 06:19 UTC, valeriano-manassero requested changes
README needs to be synced

2023-08-30 06:19 UTC, valeriano-manassero commented on charts/clearml/templates/serviceAccount.yaml
> +  name: clearml-core
EOF blank line missing

2023-09-18 13:25 UTC, valeriano-manassero approved these changes

2023-09-18 13:50 UTC, valeriano-manassero commented
@thoraxe I did some changes to reach CI ok status.
Would you mind to check just to be sure this is what you needed in this PR?

2023-09-26 18:39 UTC, thoraxe commented
It looks like it does the job to me -- it adds a default service account for the core components with a value. Thanks for cleaning up my mess!

2023-09-27 07:19 UTC, merged